[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

# aarch64 musl clear_cache
[target.aarch64-unknown-linux-musl]
rustflags = ["-C"  , "link-arg=-lgcc_s"]
