
name: Build Packages

on:
  push:
    branches:
      - main
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "files/**"
      - "src/**"
      - "vendor/**"
      - ".github/workflows/build.yml"

env:
  GITHUB_TOKEN: ${{ github.token }}


jobs:
  build:
    name: build package for  ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Linux-x86_64
            runs_on: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - name: Linux-aarch64
            runs_on: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - name: Windows-x86_64
            runs_on: windows-latest
            target: x86_64-pc-windows-msvc
          # - name: MacOS-x86_64
          #   runs_on: ubuntu-latest
          #   target: x86_64-apple-darwin
          # - name: MacOS-aarch64
          #   runs_on: ubuntu-latest
          #   target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: lilguy
          target: ${{ matrix.platform.target }}
